### ISSUE TITLE
I want to change the blacklist UI.

### ISSUE THREAD

**Issue by excorp** [Slothpala/RaidFrameSettings#15]
![image](https://github.com/Slothpala/RaidFrameSettings/assets/3642914/51f6395c-9780-4c1e-87c0-6756ee45cd00)

I'd like to make this change, and if you're okay with that, I'd like to go ahead and do it.

**Comment by Slothpala** [comment]
Hey, I am also working on the exact same thing, but with an icon of the spell. But since you have already done it? create a PR if you think it' ready.

**Comment by excorp** [comment]
#16 I registered. 
I don't know how to do it, but it would be great if it came with an icon.

**Comment by Slothpala** [comment]
#18
