### ISSUE TITLE
Can I register my personal modified version on curseforge or something?

### ISSUE THREAD

**Issue by excorp** [Slothpala/RaidFrameSettings#44]
I wanted to send an email, but I couldn't find the email address, so I'm opening an issue.

I renamed your addon to RaidFrameSettings_Fork and made some personal modifications and distributed it to my friends. 
They want it to auto-update, do you mind if I upload my modified version to curseforge,wago?

I apologize if this is inconvenient.

My modified version is currently available for distribution [here.](https://github.com/excorp/RaidFrameSettings/releases)

**Comment by Slothpala** [comment]
Hey, this is fine by me, but please name it RaidFrameSettings_excorp_fork or something like that and use a different icon so that it is clearly distinguishable from the main addon.

**Comment by excorp** [comment]
> Hey, this is fine by me, but please name it RaidFrameSettings_excorp_fork or something like that and use a different icon so that it is clearly distinguishable from the main addon.

Yes, I get it, thank you!! I'll change the name and icon.
