### ISSUE TITLE
About rolling back SpellGetVisibilityInfo 

### ISSUE THREAD

**Issue by excorp** [Slothpala/RaidFrameSettings#51]
I don't have your contact info, so I'm registering an issue.
(Oh, and by the way, my contact info is excorp79@gmail.com.)

I saw in your recent commits that you rolled back SpellGetVisibilityInfo() due to a taint issue.
However, I'm using the SpellGetVisibilityInfo function prehooked, and this is not causing the ADDON_BLOCKED_ERROR.
The taintLog says it was tainted, but that doesn't seem to be causing the error.

Or is there some behavior that I'm not aware of that is causing the error? 
If you know anything, please let me know. Thanks.

**Comment by Slothpala** [comment]
Hey thanks, I will contact you there in the next few days and explain the reasons why I have decided to change this.
