### ISSUE TITLE
Watchlist and blacklist

### ISSUE THREAD

**Issue by mantibor** [Slothpala/RaidFrameSettings#54]
Seems like a have an issue with buff and debuffs watchlist and blacklist since they don't work as intented and don't hide or show auras, somehow the only version that actually works correctly is v2.26.1.

**Comment by Slothpala** [comment]
I will push another update soon. Please let me know if this solved your issue.

**Comment by mantibor** [comment]
Still neither watchlist nor blacklist works as intended.

**Comment by Slothpala** [comment]
Please give more detail. What game version are you talking about and do you have Buffs and/or Debuffs enabled ?

**Comment by mantibor** [comment]
I am talking about Retail. I use default blizzard raid buffs and seems like addon works only if I enable buffs/debuffs in RFS. As I said before in v2.26.1 watch/blacklist works well with default buffs and debuffs.

**Comment by Slothpala** [comment]
Ah okay yea i changed the way this was handled for taint reasons. They only work with Buffs and/or Debuffs enabled. Don't expect any major changes until War Within. I am currently redoing the addon from scratch.
