### ISSUE TITLE
Stacks of some debuffs are not showing in Mythic+

### ISSUE THREAD

**Issue by kpontussvensson** [Slothpala/RaidFrameSettings#56]
**Describe the bug**
There are certain debuffs where the stacks just won't show for me in a key, it happens every run in a key but I can't replicate it in a normal/heroic/m0. I get no lua errors or anything that would indicate something is wrong otherwise. I've tested it with only RaidFrameSettings enabled and I still get the same results.

The places where it's happening every time in a key for me that I know is:

- In Ruby Life Pools I won't see the stacks off the Primal Chill debuff that you get from being hit by the whelps on first boss/in the first area.
- In Algeth'ar Academy I see the Mana Bombs stacks on Vexamus, I see the poison stacks on the tree boss but I don't see the stacks of Overwhelming Power on the last boss.

**To Reproduce**
1. Start a key of RLP (only reproducible in m+)
2. See if you see the amount of stacks of the debuff on the tank on first boss when the whelp comes.

**Expected behavior**
The stacks should show.

**Have you disabled all other add-ons?**
Yes

**Game Version**
10.2.7

**Comment by kpontussvensson** [comment]
https://github.com/Slothpala/RaidFrameSettings/assets/34517108/5f8553f1-4b18-4c60-8cdf-1d34abc3c7c5

Short video above because of the GitHub size limit. Longer video below:
https://streamable.com/rnvnpl

Only RaidFrameSettings and SharedMedia enabled on that test.

**Comment by excorp** [comment]
For debuffs with no duration, no cooldown is shown. The stack is under the cooldown, so if the cooldown is not shown, the stack is not shown either. I've made a pull request for this before. 

https://github.com/Slothpala/RaidFrameSettings/pull/37

Now I'm using a different workaround.

in Buffs.lua

```
stackText:SetParent(cooldown)

->

local textFrame = CreateFrame("Frame", nil, buffFrame)
buffFrame.textFrame = textFrame
textFrame:SetAllPoints(buffFrame)
textFrame:SetFrameLevel(buffFrame.cooldown:GetFrameLevel() + 1)
stackText:SetParent(textFrame)
```

However, creating an extra frame in this way seems to be a speed penalty.

**Comment by kpontussvensson** [comment]
Ah, it makes sense. I'll grab the workaround for now and hope that it makes it into the main version as well. Thank you @excorp.

Do you have a PR open with the new workaround you're using?

**Comment by excorp** [comment]
The code in #37 should do the trick. Creating new frames also works, but I'm not sure which is better, as creating a lot of frames seems to cause momentary lag on named names like Volcoross. So I didn't create a pull request that generates a frame.

**Comment by kpontussvensson** [comment]
Okay. I just saw that #37 was closed.

**Comment by Slothpala** [comment]
Hey, I am aware of the problem! I am currently working on a complete rewrite of the addon. The new version will move away from reusing Blizzard's aura indicators and I will create my own "class/template" (mix of xml and lua) of aura indicators. I won't be spending much time on the old code anymore.

**Comment by Slothpala** [comment]
I will look into #37 and apply a temp fix

**Comment by kpontussvensson** [comment]
Sounds good! 👍

**Comment by Slothpala** [comment]
Just wanted to let you know that I've uploaded the 3.0.0 beta to Curseforge. If you're interested, you can test it now. Just a heads-up, though, that you'll lose your settings. That's why I'm waiting with the release until after the patch.

**Comment by kpontussvensson** [comment]
Cool, I'll try it out over the next couple of days and see if I notice any problems.

I've another issue at times where 1 party member doesn't get the debuff color working but I haven't isolated that with only RaidFrameSettings enabled since it's also very random and hard to replicate so I haven't created an issue for it. It's been like that since as long as I remember so it's not something in the latest releases or so, I think I commented about it on CurseForge a couple of months ago, have you had that happen to you at all?

**Comment by Slothpala** [comment]
The Aura Highlight module has been replaced by Debuff Highlight and Buff Highlight and the entire backend of the addon has been changed. The new HealthColor.lua file now always controls the color management of the addon, which fixes some issues in general. I will close all old issues and PRs soon, as it's basically a new addon with some reused aspects.
