### ISSUE TITLE
Catacylsm - Fonts not applying on some party members who joined

### ISSUE THREAD

**Issue by muleyo** [Slothpala/RaidFrameSettings#57]
**Describe the bug**
Fonts are not properly applying on new party members

**Have you disabled all other add-ons?**
Yep.

**Screenshots**
![image](https://github.com/Slothpala/RaidFrameSettings/assets/32986026/440b6398-1f78-4083-9066-c1ae472df9db)

**Game Version**
4.4.0

**Comment by Evilholy** [comment]
Having the same issue and it's driving me mad. Usually fixes itself with a /reload but having to do that constantly is pretty annoying.

**Comment by Slothpala** [comment]
Hey currently really buisy with getting my addons ready for tww. I will only have time to look into classic once I am done with the retail versions.

**Comment by muleyo** [comment]
I'll look into it soon and fix it. no worries, appreciate your work mate

**Comment by muleyo** [comment]
I've created a pull request.

`DefaultCompactUnitFrameSetup` is only getting called before the player joins the group and therefore the fonts cant be applied.

**Comment by muleyo** [comment]
@Slothpala dont want to bug you, but could you take a quick look into my pull request? shouldn't take longer than 30sec of your time.

**Comment by Slothpala** [comment]
No worries. Thanks for looking into it!
