### ISSUE TITLE
3.0.0 beta feedback

### ISSUE THREAD

**Issue by kpontussvensson** [Slothpala/RaidFrameSettings#59]
Hey,

I'm creating a separate issue for this one that I will update with issues that I stumble upon while testing out the new beta build. I will do some dungeons and raids and keep reporting. Thanks a lot for your work, it looks really good so far and the options are really easy to set up. I got everything back to how I had it (with editing the SavedVariables file to get all my Increased auras back quickly) within 5 minutes.

## Issues

1. (SOLVED, issue on my end) First off I immediately get a lua error when I log on:
<details>
  <summary>Click to open</summary>

```
2x RaidFrameSettings/Modules/DebuffHighlight.lua:12: Cannot find a library instance of "LibCanDispel-1.0".
[string "=[C]"]: in function `error'
[string "@AstralKeys/Libs/LibStub/LibStub.lua"]:38: in function `LibStub'
[string "@RaidFrameSettings/Modules/DebuffHighlight.lua"]:12: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "LibCanDispel-1.0"."
```
</details>

2. (SOLVED, issue on my end) As soon as I enter the options and when I change anything inside the options I get the following lua error, the change does happen though:
<details>
  <summary>Click to open</summary>

```
72x Invalid Custom Control Type - SFX-Header
[string "@BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1388: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1110>
[string "@BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1137: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1110>
[string "@BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1639: in function `FeedGroup'
[string "@BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1919: in function `Open'
[string "@RaidFrameSettings/Options/OptionsFrame.lua"]:180: in function <...ceRaidFrameSettings/Options/OptionsFrame.lua:178>
[string "=[C]"]: in function `Show'
[string "@RaidFrameSettings/Core.lua"]:52: in function `?'
[string "@AstralKeys/Libs/AceConsole-3.0-7/AceConsole-3.0.lua"]:94: in function `?'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5422: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5074: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5110: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

Locals:
appName = "RaidFrameSettings_General_Options_Tab"
options = <table> {
 type = "group"
 name = ""
 args = <table> {
 }
 inline = true
 handler = <table> {
 }
}
container = <table> {
 OnWidthSet = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIContainer-InlineGroup.lua:37
 parent = <table> {
 }
 OnAcquire = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIContainer-InlineGroup.lua:19
 userdata = <table> {
 }
 children = <table> {
 }
 OnHeightSet = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIContainer-InlineGroup.lua:47
 type = "InlineGroup"
 AceGUIWidgetVersion = 22
 LayoutFinished = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIContainer-InlineGroup.lua:32
 titletext = FontString {
 }
 width = "fill"
 events = <table> {
 }
 LayoutFunc = <function> defined @BagSync/libs/AceGUI-3.0/AceGUI-3.0.lua:675
 base = <table> {
 }
 frame = Frame {
 }
 content = Frame {
 }
 SetTitle = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIContainer-InlineGroup.lua:27
}
rootframe = <table> {
 OnRelease = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIContainer-ScrollFrame.lua:48
 OnWidthSet = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIContainer-ScrollFrame.lua:152
 OnAcquire = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIContainer-ScrollFrame.lua:43
 userdata = <table> {
 }
 status = <table> {
 }
 scrollframe = ScrollFrame {
 }
 OnHeightSet = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIContainer-ScrollFrame.lua:158
 type = "ScrollFrame"
 AceGUIWidgetVersion = 26
 LayoutFunc = <function> defined @BagSync/libs/AceGUI-3.0/AceGUI-3.0.lua:656
 base = <table> {
 }
 LayoutFinished = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIContainer-ScrollFrame.lua:134
 events = <table> {
 }
 FixScroll = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIContainer-ScrollFrame.lua:91
 children = <table> {
 }
 SetStatusTable = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIContainer-ScrollFrame.lua:144
 MoveScroll = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIContainer-ScrollFrame.lua:77
 frame = Frame {
 }
 SetScroll = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIContainer-ScrollFrame.lua:59
 localstatus = <table> {
 }
 content = Frame {
 }
 scrollbar = AceConfigDialogScrollFrame1ScrollBar {
 }
}
path = <table> {
 1 = "RaidFrameColor"
 2 = "header_1"
}
group = <table> {
 type = "group"
 name = "Health Color Settings"
 args = <table> {
 }
 order = 1
 inline = true
 desc = "Health Color Settings"
}
inline = true
keySort = <table> {
 1 = "header_1"
 2 = "health_bar_foreground_color_mode"
 3 = "health_bar_foreground_use_gradient_colors"
 4 = "health_bar_foreground_static_normal_color"
 5 = "health_bar_foreground_static_min_color"
 6 = "health_bar_foreground_static_max_color"
 7 = "header_2"
 8 = "health_bar_background_use_gradient_colors"
 9 = "health_bar_background_static_normal_color"
 10 = "health_bar_background_static_min_color"
 11 = "health_bar_background_static_max_color"
 12 = "header_3"
 13 = "power_bar_foreground_color_mode"
 14 = "power_bar_foreground_use_gradient_colors"
 15 = "power_bar_foreground_static_normal_color"
 16 = "power_bar_foreground_static_min_color"
 17 = "power_bar_foreground_static_max_color"
 18 = "header_5"
 19 = "power_bar_background_use_gradient_colors"
 20 = "power_bar_background_static_normal_color"
 21 = "power_bar_background_static_min_color"
 22 = "power_bar_background_static_max_color"
}
opts = <table> {
 header_3 = <table> {
 }
 power_bar_background_static_min_color = <table> {
 }
 health_bar_foreground_static_min_color = <table> {
 }
 health_bar_foreground_static_normal_color = <table> {
 }
 health_bar_foreground_color_mode = <table> {
 }
 header_1 = <table> {
 }
 power_bar_foreground_static_min
```
</details>

3. The debuff frame's anchoring is inconsistent whether an Enlarged aura or a normal aura is the first aura. I use the following position settings:
<details>
  <summary>Click to open</summary>

```
Anchor point: Bottom Left
Relative point: Bottom Left
Horizontal offset: 1
Vertical offset: 10
```
See the video: 

https://github.com/Slothpala/RaidFrameSettings/assets/34517108/34986165-19b1-4fb3-8028-4947c5bbc23a
</details>

## Feature requests
1. I would personally like it a lot if the debuffs/buffs watchlist and blacklist were alphabetically sorted by name (just to make sure you don't sort it by spell id if you end up doing this), it's a bit hard to find specific auras in the list if you have a lot of them. I personally use the increased auras as a way to emphasize dangerous dots and debuffs in mythic+ so my list usually gets quite extensive.
2. Add the option to change the increase_factor again, I see that you have it in the Database.lua but I can't find it in the options.

**Comment by Slothpala** [comment]
Thanks for the feedback! Points 1&2 are about your personal setup.
Point 3: I will change the anchors. 
Feature request: I will think about point 1 and yes, point 2 is just a missing slider. It will be added!

**Comment by kpontussvensson** [comment]
> Thanks for the feedback! Points 1&2 are about your personal setup.

Aren't the Libs supposed to be included in the release? They are not included in the zip from the release section which is what causes these errors. https://github.com/Slothpala/RaidFrameSettings/releases/tag/3.0.0-beta3

If I only enable RaidFrameSettings on the 3.0.0 beta I get even more errors because of missing libs.

**Comment by Slothpala** [comment]
Ah, have you used the git version before? If so, you will need to install the following dependencies: Ace3, LibDeflate, LibSharedMedia-3.0, AceGUI-3.0-SharedMediaWidgets, LibDDI-1.0, AceGUI-3.0_SFX-Widgets, LibCanDispel-1.0, LibDBIcon-1.0, LibCustomGLow-1.0

**Comment by Slothpala** [comment]
These are specified in the toc file.

**Comment by ccpoppin1** [comment]
RFS - causing "existing profiles" in other addons to disappear 

**Describe the bug**
When RFS is enabled, it is causing existing profile options to disappear in other addons, notably 'Plater'. There could be issues with others.

Additionally, there is no "existing profiles" option in the RFS addon itself. Is this correct? I believe there should be.

Please see attached screenshots for context.

Other than that, the addon is great I want to say thank you for the support! 

RFS - disabled - plater options show working as intended.
![rfs - disabled plater](https://github.com/user-attachments/assets/5ad811e1-77fc-49f5-b4f3-918f6dbf1897)
RFS - enabled - plater options showing no existing profiles when there is.
![rfs - enabled - plater error](https://github.com/user-attachments/assets/a6ce0960-d0df-46be-b6f9-877f5f817b8c)
RFS addon - no existing profiles by default.
![rfs - no existing profile option](https://github.com/user-attachments/assets/a897bd7c-14c4-437e-85ab-454eb1a91558)

**Comment by ccpoppin1** [comment]
Hi Slothpala, thanks for the quick response to the issue I referenced above.

It appears to be showing now, but another issue has popped up. I can load existing profiles now on RFS and other addons but it does not stick on RFS (it appears other addons like Plater stay loaded). Once I log out/reload the profile resets to 'Default'.

**Comment by Slothpala** [comment]
Profiles load based on group profile settings.
