### ISSUE TITLE
RFS - causing "existing profiles" in other addons to disappear 

### ISSUE THREAD

**Issue by ccpoppin1** [Slothpala/RaidFrameSettings#60]
**Describe the bug**
When RFS is enabled, it is causing existing profile options to disappear in other addons, notably 'Plater'. There could be issues with others.

Additionally, there is no "existing profiles" option in the RFS addon itself. Is this correct? I believe there should be.

Please see attached screenshots for context.

Other than that, the addon is great I want to say thank you for the support! 

RFS - disabled - plater options show working as intended.
![rfs - disabled plater](https://github.com/user-attachments/assets/5ad811e1-77fc-49f5-b4f3-918f6dbf1897)
RFS - enabled - plater options showing no existing profiles when there is.
![rfs - enabled - plater error](https://github.com/user-attachments/assets/a6ce0960-d0df-46be-b6f9-877f5f817b8c)
RFS addon - no existing profiles by default.
![rfs - no existing profile option](https://github.com/user-attachments/assets/a897bd7c-14c4-437e-85ab-454eb1a91558)

**Comment by Slothpala** [comment]
Thanks for reporting.
