### ISSUE TITLE
Spirit Wolf (Shaman stacking DR while in Ghost Wolf) doesn't display stack count

### ISSUE THREAD

**Issue by hianick** [Slothpala/RaidFrameSettings#61]
**Describe the bug**
When you take the talent "Spirit Wolf" in the shaman class tree, you get a buff that stacks up to 4 after you stay in ghost wolf form, but stacks arent displayed on party frames.

**To Reproduce**
1. Log into a shaman
2. Add "260881" to watchlist.
3. Take the talent spirit wolf, 2nd row, middle column.
4. Shift into ghost wolf, wait a few seconds for it to stack up.
5. Duration is missing as expected, but stack count is also missing.

**Expected behavior**
Should be able to see stacks.

**Have you disabled all other add-ons?**
Yes

**Screenshots**
[Also included earth shield with stacks, and next to default aura icons.](https://imgur.com/a/2Mthbxs)

**Game Version**
10.2.6.55664
addon version 2.30.2

**Additional context**
edit, same issue on every shaman spec.

**Comment by Slothpala** [comment]
I no longer maintain version 2.30.2
