### ISSUE TITLE
[Feature Request] Increase aura group offset

### ISSUE THREAD

**Issue by edumserrano** [Slothpala/RaidFrameSettings#63]
The horizontal and vertical offsets in aura groups are limited to a range between -10 and 10. This is a very low offset range. Is it possible to remove this limitation?

I currently use [Enhanced Raid Frames](https://www.curseforge.com/wow/addons/enhanced-raid-frames) and I configure my resto druid heal over time buffs to show on a 2x3 matrix on the bottom right of the frame as shown by this image:

![image](https://github.com/user-attachments/assets/0872dbc6-bcd6-47f9-ad14-c4ab68b78c5a)

The buffs are always on that position. It's a fixed position per hot. Using Enhanced Raid Frames I achieve this by:

1) Selecting which hot should be displayed in the bottom left, bottom, bottom right, center and right indicators
1) Setting the proper horizontal and vertical offsets for the bottom left, bottom, bottom right, center and right indicators so that they look like a 2x3 matrix.

Currently I cannot achieve this with Raid Frame Settings because of the limit on the horizontal and vertical offsets in the aura groups.

**Comment by Slothpala** [comment]
Done! 085565813c9f3c0dc0a338cb1732cbad16677282
