### ISSUE TITLE
[Feature Request] Be able to resize the addon

### ISSUE THREAD

**Issue by edumserrano** [Slothpala/RaidFrameSettings#65]
Even with the scale option on the top left of the addon RFS looks like this to me:

![image](https://github.com/user-attachments/assets/3155b57b-f7c3-406a-9b90-63fd3df5463f)

Would it be possible to resize the addon window? The main issue I have at the moment is with seeing the list of spells in things like the Blacklist.

**Comment by Slothpala** [comment]
That's what the "Hide Settings" option is for, I'll think about adding a resize option, I like the fixed size more since the content of most tabs doesn't scale well. Maybe I will add a button to open the list in a separate scalable window.
