### ISSUE TITLE
Suggestion: add the ability to show the duration of buffs and debuffs

### ISSUE THREAD

**Issue by Soulpala** [Slothpala/RaidFrameSettings#7]
As can be guessed from the title, I was wondering if there was a possibility to show a text with the duration of buff and debuff. Thank you!

**Comment by excorp** [comment]
https://imgur.com/a/PxtTHa6

I'm using the omnicc add-on, so I'm seeing the time remaining.
However, it would be nice if the RFS add-on could display the time itself.

**Comment by excorp** [comment]
https://imgur.com/a/PxtTHa6

I was using the OmniCC add-on, so it was showing me the remaining time. 
However, it would be nice to see it even if not using OmniCC. 
It would also be nice to be able to set the position, size, and appearance in options.


buffFrames[1].cooldown:SetHideCountdownNumbers(false)

I've tested this command to show the cooldown count and it works.
but it only works if the countdownForCooldowns Cvar is set to true.

So I think it would be better to create a separate cooldown frame and attach it. 
OmniCC users may want to call OmniCC.Cooldown.SetNoCooldownCount() to avoid duplicate numbers.

**Comment by Slothpala** [comment]
Not my focus at the moment, maybe in the future.

**Comment by Slothpala** [comment]
#18
