### ISSUE TITLE
[Feature request] Hiding of Duration text

### ISSUE THREAD

**Issue by jrysz** [Slothpala/RaidFrameSettings#73]
When I am playing my shaman I would like to be able to hide the Duration text of Earth Shield and only show the stacks.

**Comment by Slothpala** [comment]
You can already hide the duration timer for each AuraFrame, or what do you mean?

**Comment by jrysz** [comment]
You're right I am blind :)

**Comment by Slothpala** [comment]
No worries :D There are a lot of options!
