### ISSUE TITLE
[Bug] Health Bar Background doesn't work when texture module is not enabled

### ISSUE THREAD

**Issue by edumserrano** [Slothpala/RaidFrameSettings#75]
**Describe the bug**

The Health Bar Background option under the general tab does not work if the Texture module is not enabled under the Module Center tab. Choosing a static color for the Health Bar Background doesn't work.

**To Reproduce**

1. Go to the Module Center tab.
2. Disable the Texture module.
3. Go to the General tab.
4. Set a static color for the Health Bar Background, something other than black. Red for instance.
5. Take some damage so that you're not at full health.
6. Notice that the Health Bar Background is black and not whatever static color you defined on step 4.

**Expected behavior**

The health bar background should still work if the Texture module is disabled.

**Have you disabled all other add-ons?**

No

**Screenshots**

This shows a configuration where the Health Bar Background is set to be red and the Texture module is disabled:
![image](https://github.com/user-attachments/assets/658e0b90-b5ed-44b3-8257-81ece9527e8a)

This shows the same configuration but now with the Texture module enabled:
![image](https://github.com/user-attachments/assets/920b74f9-77b3-4864-9c38-83c857b0d76d)

**Game Version**
11.0.2.56313

**RFS Version**
3.0.18

**Additional context**

In case it helps, the Health Bar Foreground does work properly with or without the Texture module.

**Comment by edumserrano** [comment]
This might not be an important bug because I guess the user can always enable textures, select the `Blizzard Raid Bar` for the Health Bar Foreground and then the Health Bar Background would work and the end result would be similar to having the texture module disabled.

Feel free to close if you don't think this matters much.

**Comment by Slothpala** [comment]
It does works! If you look closely, the color in your screenshot actually has a slight red tint to it. This is just how the color looks on this texture.
