### ISSUE TITLE
[Feature Request] Textures on `Dispel Colors`

### ISSUE THREAD

**Issue by edumserrano** [Slothpala/RaidFrameSettings#76]
Hey @Slothpala, it's me again 😅

## Request

I was wondering what are your thoughts on adding a texture option for the `Dispel Colors` under the `Addon Colors` tab ?

My main case is that there are so many classes in the game that it's hard to find a a set of colors for the dispel categories that doesn't slightly overlap with some class color in the game. For instance the default color for `Magic` is close to the Mage's class color and it's not that different from the Shaman's class color. The default color for `Disease` is close to a warrior's class color. 

Having the dispel colors close to a class color and having the unit frames class colored means it's sometimes harder to spot when a certain debuff is applied. Maybe the small color difference between the dispel color and the class color is more than enough for most people and perhaps I just have a bit of a hard time with similar colors.

As such I was thinking if it was possible to add a texture option to make it more obvious. The idea would be that the texture would be applied in addition to the select color for the dispel color. And although you could enable the user to select a preferred texture and you could have different textures per dispel category, having an on/off texture toggle that applies a default texture would be enough for a first version I suppose. Something like plater's focus texture:

![image](https://github.com/user-attachments/assets/03565c1c-a957-4a5f-959c-b363bd774ea1)

## Workaround

As a workaround what I sometimes do is set the health bar to be of a static color, like black, instead of class color so that the dispel colors are always easily visible.

**Comment by Slothpala** [comment]
Hi again :D 

Yes, that is doable! I will implement it in a future update, I like the idea!

**Comment by edumserrano** [comment]
This looks awesome. Since the update with this change I haven't had any confusion between dispel colours and class colours. 

Thank you @Slothpala 🎉
