### ISSUE TITLE
The anchor of the Name Text is wrong

### ISSUE THREAD

**Issue by kpontussvensson** [Slothpala/RaidFrameSettings#79]
With the new update pushed today (version 3.0.23) the Name Text got pushed super far to the right. Before i had horizontal offset +2 and it was basically next to the left edge as it should with Anchor point: Top Left and Relative Point: Top Left. Now it's pushed super far to the right, even with Horizontal offset: -10 it's still not positioned correctly. See screenshot:

![RFS](https://github.com/user-attachments/assets/cbda8d62-aea7-426f-9f19-dbe97269fea9)

**Comment by Slothpala** [comment]
JustifyH to Left

**Comment by kpontussvensson** [comment]
Aah, is that a new option or did it reset for some reason?

**Comment by Slothpala** [comment]
No, it was there since the rework, but never really worked before the resent changes because I forgot to set a width to the font string.

**Comment by kpontussvensson** [comment]
Alright, it's solved now. Cheers!
