### ISSUE TITLE
Fonts JustifyH not updating on its own

### ISSUE THREAD

**Issue by K4r4zh4n** [Slothpala/RaidFrameSettings#80]
The "JustifyH" option for names (and maybe others) only shows changes after something else gets updated, 
like the Horizontal or Vertical offset, making it look like the option does nothing while configuring the addon.

(took me some time to notice, so for a while I thought the anchor points were broken :) 

Maybe this is intended, wanted to let you know, just in case :) 

Thanks for the fantastic addon <3

**Comment by Slothpala** [comment]
If you are talking about retail. No, it updates immediately, maybe it is due to another addon.

Nice to hear that you like the addon! :-)

**Comment by K4r4zh4n** [comment]
Same behavior with RFS being the only addon, but I assume it is just a problem on my client for some reason, no worries :)
