### ISSUE TITLE
[Suggestion] Hide raid buffs when party and raid member have it on.

### ISSUE THREAD

**Issue by Revnn** [Slothpala/RaidFrameSettings#81]
Currently, the raid buffs (fortitude, mark of the wild, etc) they show all the time outside combat when you play their class.
Would it be possible to only show/track whenever a party or raid member is missing your class buff?

**Comment by Slothpala** [comment]
That is already possible with aura groups. I could add a pre-set for it.

**Comment by Revnn** [comment]
Ahhh i didnt know that, managed to set it and its perfect. ty.
